### ISSUE TITLE
Upgrade plans to Popper v1?

### ISSUE THREAD

**Issue by FezVrasta** [antongorodezkiy/vue-popper-component#1]
Hi, thank you for the great component!

I was wondering if you have any plans to upgrade this component to Popper v1.

In few days we'll release the first stable beta, but the API of the latest alpha is already stable.

Thank you.

**Comment by antongorodezkiy** [comment]
Hello @FezVrasta 

I must to thank you! popper.js is great

Sure, I'll upgrade it, will try to upgrade this week.

**Comment by FezVrasta** [comment]
Hi, just an heads up, we reached beta.3 right now, if no bug raises in the next week, I'm going to promote this beta.3 to RC and move out of beta officially.

Do you plan to upgrade to v1 in time for the release?

**update**: v1 is out

**Comment by antongorodezkiy** [comment]
Thanks @FezVrasta 

I've just released https://github.com/antongorodezkiy/vue-popper-component/releases/tag/0.0.4 with Popper.js 1.* support
