### ISSUE TITLE
Rename `demo` to `docs` and enable gh-pages

### ISSUE THREAD

**Issue by FezVrasta** [antongorodezkiy/vue-popper-component#2]
Hi, you could rename the `demo` folder to `docs` and i the repository settings enable the gh-pages served by `docs`. Doing so, visiting https://antongorodezkiy.github.io/vue-popper-component will open the demo page.

**Comment by antongorodezkiy** [comment]
@FezVrasta good idea, thanks!

**Comment by antongorodezkiy** [comment]
Added demo page
